### ISSUE TITLE
Faculty class selection better formatted

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#16]
Currently future class selection are given as multiple tabs. Should put under one tab with perhaps pull down menu to select the semester.

**Comment by pluskid** [comment]
fixed in revision 223.

**Comment by samanamarasinghe** [comment]
Can you do the same for /lects/class assignments

**Comment by pluskid** [comment]
fixed in revision 230.

**Comment by samanamarasinghe** [comment]
Most faculty will have only one assigned class. I think it is too verbose for them to go to assign class list and select one class. Can you show the list of courses only when there is more than one and have a tab that will directly go to the class if there is only one (as it was before)?

**Comment by pluskid** [comment]
@samanamarasinghe now implemented.
