### ISSUE TITLE
Summary by class Number of TA slots don't work

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#19]
Planning classes --> Summary by class NUmber of TA slots cannot be used to modify the slots.

**Comment by pluskid** [comment]
fixed in revision 205
- staffslots function is missing
- when switched from "Half TA" to normal TA, the staff_exception status should be removed

**Comment by samanamarasinghe** [comment]
Lets talk about this on Monday. 

-Saman
