### ISSUE TITLE
Add more fields to student

### ISSUE THREAD

**Issue by pluskid** [mit-eecs/issue-tracker#2]
Descriptive department is needed, not course number.

**Comment by pluskid** [comment]
@samanamarasinghe when the model fields changes, do we need to do something to the database (manually)?

**Comment by samanamarasinghe** [comment]
Yes, need to do syncdb, but there is a special server to do that (look in the docs of scripts.mit.edu). I normally login to sql.mit.edu and add the fields manually.

-Saman

**Comment by pluskid** [comment]
- field `fte` added

**Comment by pluskid** [comment]
- field `department` added, with default value `Electrical Engineering and Computer Science`

**Comment by pluskid** [comment]
field `ta_type` added, see #3

**Comment by pluskid** [comment]
`ta_type` is now editable in TA Offer process.
