### ISSUE TITLE
Timestamps class

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#26]
Right now all the status updates when student is offered a position, accept, decline etc. is kept as a ascii text in notes field. Instead create a timestamps class that keep student info, status change data and time, update originator

**Comment by pluskid** [comment]
@samanamarasinghe Is there a model for "user" in the DB? I'm trying to create the timestamp class and record **who** made the update. But it seems lecturer, admin and student are three different kind of users in the system? Maybe store the athena username here? How could we get the current athena username?

**Comment by pluskid** [comment]
`StatusChange` is defined to record status changes of students. Current stta_update will add entries with this instead of plain text notes.
