### ISSUE TITLE
Safari has certification problem

### ISSUE THREAD

**Issue by pluskid** [mit-eecs/issue-tracker#28]
It seems some student is having problem login with safari because of certificate problem.

**Comment by pluskid** [comment]
This might be safari's own bug. Safari has a lot of issues related certificates. I myself have some problems accessing some other websites of MIT requiring personal certificates.

**Comment by samanamarasinghe** [comment]
Perhaps put a warnning...especially if Safari goes to the page that says no registration found, we can put a comment about supported browsers there.

**Comment by pluskid** [comment]
I have put a note to encourage trying with Firefox or Chrome on the page of invalid certificate ID. Though I'm not sure yet whether people will see that page if the issue is with the certificate.
