### ISSUE TITLE
Tabs in Jquery UI

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#30]
Current tabs are in a self made form, should move to Jquery UI tabs

**Comment by pluskid** [comment]
/lects/ sub-site not converted yet.

**Comment by samanamarasinghe** [comment]
I don’t like the red background on the tabs. It should be the same as the normal background. Also, the background is set to white inside the tabs, which should be again the normal background for that section (i.e. blue for staff).  Once you got the tabs working for lects, we can release the entire update.  Can you get that done before we meet?

-Saman

**Comment by pluskid** [comment]
The colors can be customizable through jquery-ui themes. I will change that.

Adapting to jquery-tabs involves some non-trivial modification. I will try to do that before 5pm today. But since I have classes through out the day and another meeting, I'm not sure it will be perfectly ready by then.

**Comment by pluskid** [comment]
Now all occurrences are supposed to be converted. If any missed ones or some bugs (like some page content are not loading) found, please re-open this.

**Comment by samanamarasinghe** [comment]
Where is the style for the tabs? Also can I have different styles for eduoffice/lects/staff?

-Saman

**Comment by pluskid** [comment]
@samanamarasinghe the theme file is put in media/css/jquery-ui-default/ . If you go http://jqueryui.com/themeroller/ , you can customize your own theme from ThemeRoller (it seems it is not possible to get transparent background from the ThemeRoller, so some post-hacking is also needed).

The theme file is for all jquery-ui widgets (not only tabs). Theoretically, we could have different look-and-feel for different sub-sites: just include different css theme will do the trick.

**Comment by samanamarasinghe** [comment]
OK, I hacked and fixed the tab background.

-Saman

**Comment by pluskid** [comment]
@samanamarasinghe Thanks a lot!

**Comment by pluskid** [comment]
It seems the theme is affecting other jquery widget. Specifically, the email preview popup dialog in email spammer now also becomes transparent and difficulty to read. Should find a way to fix this.

**Comment by pluskid** [comment]
fixed.
