### ISSUE TITLE
Capabilities/preferences for faculty

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#33]
If any faculty member is assigned to a subject, the will 1) get to select TAs  2) will get all the e-mail about  TA assignments etc.  We need the ability to say if a faculty member is involved or not in the TA selection process. If he/she is not involved, he/she cannot select the student preferences (can see the current lists, but not select) and also should not get e-mail when TA assignments, selections etc. happens.

**Comment by pluskid** [comment]
I find there is a `title` field in lectuerterm: `Lecturer`, `CoLecturer` and `Recitation Instructor`. I'm not sure about the logic here: Shall we use this field to decide the lecturer's ability to be involved in TA selection process, or shall we add a new field in lectureterm like `ta_involvement` specifically to indicate this ability?

**Comment by samanamarasinghe** [comment]
It is for any additional title like dept, chair. We are not using it for anything useful.

**Comment by pluskid** [comment]
fixed in revision 329.
Now LectureTerm has a field ta_admin (default `True`), editable in eduoffice. When this field is off, lecturer cannot select or rate the TAs in the corresponding course.
