### ISSUE TITLE
TA stipend calculation does not work

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#34]
I think the logic is wrong... need to be updated/corrected.

**Comment by samanamarasinghe** [comment]
In order for us to give a salary have to be a 
normal teaching assistant, 
selected only for a single subject, 
from EECS
have a FTE of 1. 
If so, lookup the salary in the database depending on ugrad/Meng/SM/PhD

**Comment by samanamarasinghe** [comment]
Or if the student has maked "has fellowship", Stipend should not be calculated.

**Comment by pluskid** [comment]
I still keep the original logic there (like st.exception things). But added testing for TA type, department, FTE, fellowship. there is only an entry current_stta, doesn't this automatically mean that a student is only selected for a single subject?
