### ISSUE TITLE
TA applicant pictures

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#35]
Ability for TA applicants to either download a photo of themselves or point to a URL with a photo. And then show that photo, if available, when the TA tooltip is displayed.

**Comment by pluskid** [comment]
Tried to use Django's ImageField, but couldn't get image uploaded. I'm a little confused by how the scripts are being hosted by script.mit.edu. Are they using the AFS directly for those files? I'm thinking of making the media directory writable to all people will allow uploading, but nothing happened, and yet there seems to be no error message.

**Comment by pluskid** [comment]
I also noticed that there are some existing code (commented out) for staff thumbnails. Should that be used?

**Comment by samanamarasinghe** [comment]
I could not get that thumbnail code to work.

-Saman

**Comment by samanamarasinghe** [comment]
Can we just ask them to put a URL for a picture, check if it is infact an image and store the URL.  When rendering the TA pages and the TA baloon force that into a tumbnail image of a fixed size.

**Comment by samanamarasinghe** [comment]
Put it in an iframe. Show the students the image when they enter the URL. Crop the image when it gets displayed.

**Comment by samanamarasinghe** [comment]
Done
