### ISSUE TITLE
Revamp e-mails

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#36]
The current e-mail messages are non-intuitive.  The primary receiver, the faculty or the TA candidates, should get more descriptive messages. The copies sent to Lisa/eduofficers should have better subject lines and reformatted bodies, perhaps with the history of that student's activities.

**Comment by samanamarasinghe** [comment]
LectureTerm has emailAlerts. that should be used to prune e-mail about TA selection and changes to the class sent to the lecturers.

**Comment by pluskid** [comment]
More information is added to the email titles.
