### ISSUE TITLE
Email spammer for the Staff

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#37]
Currently only faculty can be sent e-mail.
Ability to select:
   Students with no preferences
    Students in different stages of selection (unselected, selected, offered, accepted, withdrawn) 
    Students who have been offered a TA position X days ago and haven't answered

**Comment by pluskid** [comment]
fixed in revision 226.

**Comment by samanamarasinghe** [comment]
space between end of students and the beginning of the next block.

Ability for Students offered by not responded to give the number of days not responded. (Or just the ability to only send mail to students where  today - last_event_timestamp > n)

**Comment by pluskid** [comment]
Fixed in revision 234.
