### ISSUE TITLE
More information in eduportal/planning classes/summary by Class

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#40]
Need to add couple more columns to this page
- Number of prereg students in the last semester
- Number of TAs assigned in the last semester
- Numeer of prereg students the semester before last
- Number of TAs assigned in the semester before last

**Comment by pluskid** [comment]
@samanamarasinghe 
There is no field in course_term recording number of TAs, when getting the number of TAs in the last term and the term before last, can I just use the # of TA slots as the # of assigned TAs? I'm not sure the logic is correct: there will always be that many TA assigned as indicated by # TA slots. If this is not true, we will need to count number of StudentTA corresponding to this course_term and with 'OFF' status.

**Comment by pluskid** [comment]
I also noticed in the beta database, there is not course_term for Fall 2011 (Term id 16). But records exists for Spring 2011.

**Comment by samanamarasinghe** [comment]
# of slots assigned is OK.  think to get the number of TAs you have to count them by filtering the studentTA table.

About the second comment. We need to revisit the integrity checking we are doing in setup.

**Comment by pluskid** [comment]
fixed in revision 238.
