### ISSUE TITLE
WHo is teaching what

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#41]
Currently we have Who is teaching what page created. It shows a single semester.
I'd like it to be more customized, i.e. able to put multiple semesters. For example, right now it would be nice to show both Fall12 and Spring13. But before Spring13 was finalized it has to be only fall 12.  The easiest way is to have a filed in settings that says only active or active and planning semesters and update the page accordingly.

**Comment by samanamarasinghe** [comment]
Add two wrappers 
https://eecs.scripts.mit.edu:444/eduportal/who_is_teaching_what/current
https://eecs.scripts.mit.edu:444/eduportal/who_is_teaching_what/next

**Comment by pluskid** [comment]
@samanamarasinghe I added the wrapper /current to show the `activeTerm` and /next to show the `planningTerm`. It seems in the current beta database, activeTerm is Spring 2012 and planningTerm is Fall 2012. Is it the database is not updated yet or I misunderstood the concept?

**Comment by samanamarasinghe** [comment]
The database was not updated.

-Saman
