### ISSUE TITLE
Allow Lecturer to add TA Rating somewhere

### ISSUE THREAD

**Issue by pluskid** [mit-eecs/issue-tracker#43]
At what stage should the lecturer be able to rate the TA?

**Comment by pluskid** [comment]
fixed in revision 231. Now TA can be rated from /lects/

**Comment by samanamarasinghe** [comment]
Right now the ratings can be seen in the tooltip popup. However, the students can also see this pop-up under class TA/staff!! STUDENTS SHOULD NOT BE ABLE TO SEE THE FACULTY EVALUATIONS OF THEM!  Make sure the popup with the student evaluation is only seen by faculty (in lects) and the eduoffice.

**Comment by pluskid** [comment]
fixed in revision 236.

**Comment by samanamarasinghe** [comment]
Rating has to happen on active semester TAs for the class the instructor is teaching in the active semester NOT planning semester classes and TAs.

**Comment by pluskid** [comment]
fixed in revision 239.
