### ISSUE TITLE
More menu items don't work

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#47]
Eduoffice --> staff --> Select Staff from list --> Next menu items such as bio information don't work. 
I think this is the updated Junit issue. You may want to go through all the menu items within eduportal and check.

**Comment by samanamarasinghe** [comment]
All the menu items under eduoffice --> Planning class does not work either

**Comment by samanamarasinghe** [comment]
"Menu" should be "Tab Select"

**Comment by samanamarasinghe** [comment]
Faculty -> Select faculty does not work...

**Comment by pluskid** [comment]
@samanamarasinghe All those actually work properly for me. I tried with Chrome and Firefox. I guess it might be because the new javascript library is not loaded yet -- if it is the problem, refresh the whole page might solve the problem.

**Comment by samanamarasinghe** [comment]
YEs, works now
