### ISSUE TITLE
Ratings is not working

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#48]
After I updated my rating of a TA. the following error occurs:

MultipleObjectsReturned at /lects/faculty_ta_rate/6/853/
get() returned more than one TARating -- it returned 2! Lookup parameters were {}

Request Method: GET
Request URL: https://eecs.scripts.mit.edu:444/eduportal-beta/lects/faculty_ta_rate/6/853/
Django Version: 1.4.2
Python Executable: /usr/bin/python
Python Version: 2.7.3
Python Path: ['/mit/eecs/Scripts/django/eduportal_beta', '/mit/eecs/Scripts/django', '/afs/athena.mit.edu/org/e/eecs/web_scripts/eduportal-beta', '/afs/athena.mit.edu/org/e/eecs/.local/lib/python2.7/site-packages/sorl_thumbnail-11.09.1-py2.7.egg', '/usr/lib/python2.7/site-packages/AuthKit-0.4.5-py2.7.egg', '/usr/lib/python2.7/site-packages/elementtree-1.2.7_20070827_preview-py2.7.egg', '/usr/lib/python2.7/site-packages/jsonlib2-1.5.2-py2.7-linux-x86_64.egg', '/usr/lib/python2.7/site-packages/pygit-0.1-py2.7.egg', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/afs/athena.mit.edu/org/e/eecs/.local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/Numeric', '/usr/lib64/python2.7/site-packages/PIL', '/usr/lib64/python2.7/site-packages/gst-0.10', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info']
Server time: Mon, 26 Nov 2012 09:19:18 -0500
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'sorl.thumbnail',
 'coursemgmt_beta')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'coursemgmt_beta.ScriptsRemoteUserMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
2.                 return view_func(request, _args, *_kwargs)
   File "/mit/eecs/Scripts/django/coursemgmt_beta/views.py" in faculty_ta_rate
3.             rate_list.append(TARatingForm(instance=ratings.get()))
   File "/usr/lib/python2.7/site-packages/django/db/models/query.py" in get
4.                 % (self.model._meta.object_name, num, kwargs))

**Comment by pluskid** [comment]
Fixed in revision 237.
