### ISSUE TITLE
Eduoffice minimal planning beyond planning semester

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#53]

**Comment by samanamarasinghe** [comment]
Since we will not be doing the semester in the URL. I'd like to see if we can get four semesters with something looking like "faculty selection". It would be just a view.  Basically one place in the eduportal to look at what each faculty has entered under "Teaching Requests for specific terms"

**Comment by samanamarasinghe** [comment]
Have the same view as Lects->Class assignment processing --> Show all requests  from the top menu of eduoffice
Also, able to select with this view vs. Each row with faculty name and each element in the gird to be a class.

**Comment by pluskid** [comment]
Fixed in revision 328. See _Class Assignments Summary_ tab in the top-level tabbar of eduoffice.

**Comment by samanamarasinghe** [comment]
Can you also list the two previous semesters?

**Comment by pluskid** [comment]
done in revision 331.
