### ISSUE TITLE
Once Staff accept or reject a TA offer returning to the wrong page

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#63]
When accept or reject offer button is pressed, the page displayed is the basic_information_page. The top page and the tabs gone

**Comment by pluskid** [comment]
Wrong redirection. Fixed.

**Comment by samanamarasinghe** [comment]
Still happening goto http://eecs.scripts.mit.edu/eduportal-beta/staff and Offer page and press accept offer

**Comment by samanamarasinghe** [comment]
fixed
