### ISSUE TITLE
In setup get rid of the extra line in uploaded data 

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#66]

**Comment by pluskid** [comment]
Fixed in revision 289.

**Comment by samanamarasinghe** [comment]
Setup it broken
setup_feedback'
Request Method: GET
Request URL:    https://eecs.scripts.mit.edu:444/eduportal-beta/eduoffice/eduoffice_setup/
Django Version: 1.4.2
Exception Type: KeyError
Exception Value:  
'setup_feedback'
Exception Location: /usr/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py in **getitem**, line 39
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:  
['/mit/eecs/Scripts/django/eduportal_beta',
 '/mit/eecs/Scripts/django',
 '/afs/athena.mit.edu/org/e/eecs/web_scripts/eduportal-beta',
 '/afs/athena.mit.edu/org/e/eecs/.local/lib/python2.7/site-packages/sorl_thumbnail-11.09.1-py2.7.egg',
 '/usr/lib/python2.7/site-packages/AuthKit-0.4.5-py2.7.egg',
 '/usr/lib/python2.7/site-packages/elementtree-1.2.7_20070827_preview-py2.7.egg',
 '/usr/lib/python2.7/site-packages/jsonlib2-1.5.2-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7/site-packages/pygit-0.1-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/afs/athena.mit.edu/org/e/eecs/.local/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/Numeric',
 '/usr/lib64/python2.7/site-packages/PIL',
 '/usr/lib64/python2.7/site-packages/gst-0.10',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info']
Server time:    Thu, 13 Dec 2012 14:55:30 -0500

**Comment by pluskid** [comment]
Fixed.
