### ISSUE TITLE
TA ratings visible and deletable by the lecturer

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#67]
Lecturer entering the
1) TA ratings should be able to see all the ratings for that students
2) should able to delete their ratings

**Comment by pluskid** [comment]
Student balloon is displayed (with TA rating). Faculty able to delete his rating.
fixed in revision 292.

**Comment by samanamarasinghe** [comment]
Remove This Rating should be deactivated if there is no rating.

**Comment by pluskid** [comment]
fixed in revision 298.
