### ISSUE TITLE
Managing TAs at the class level from eduoffice

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#69]
If you are a lecturer, you  can look at all the TAs applicants for your class.  However, from eduoffice there is no way to select a single class and manage the ta applicants to that class.
See Staff --> capability to teach eduoffice where you can manage each student. Need to have somthing similar for the eduoffice -->  courses.

**Comment by samanamarasinghe** [comment]
Note::  Planning Classes --> Planning classes now displays the TA selection, but cannot select a TA or unselect him etc. from here. Should give me more options (as within Eduoffice --> Staff -> capability to teach) from here NOT from eduoffice --> courses.

**Comment by pluskid** [comment]
fixed in revision 322. Now similar operations like TA Offer Process are available in planning course.
