### ISSUE TITLE
Exceptions editable in eduoffice--> planning classes --> TA offer process

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#71]

**Comment by pluskid** [comment]
Currently both student.exception and student.curr_stta.course_term.staff_exception is displayed in the table cell. Which attribute shall we make editable?

**Comment by pluskid** [comment]
@samanamarasinghe Currently both student.exception and student.curr_stta.course_term.staff_exception is displayed in the table cell. Which attribute shall we make editable?

**Comment by samanamarasinghe** [comment]
Can you create an editing dialog box that displays both on separate boxes? So you can edit each separately?

-Saman

**Comment by pluskid** [comment]
Fixed in revision 326.

**Comment by samanamarasinghe** [comment]
The pencil graphic is too much. Can you just leave it same as done with editing FTE?

**Comment by pluskid** [comment]
@samanamarasinghe Sure. But I need to put something there so that when the exception is empty string (""), we can still have something to click on.

**Comment by samanamarasinghe** [comment]
Can you do that only on an empty string?  I just put “.”

In Planning à Summary by Class   the field CEO-only Notices.  The pencil is too distracting. 

-Saman

**Comment by pluskid** [comment]
Now pencil is replaced with a dot, and only displays when the text is empty.
