### ISSUE TITLE
Semester dates in offer letters

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#72]
Right now the start and end of the semester is hard coded in the offer letter. Should have a tag %SEMESTERDATES% that will put the right dates (perhaps fhardcoded in settings.py depending in spring or fall and get the year from term)
Spring Jaunary 15 to May 31
Fall September 1st to January 14

**Comment by pluskid** [comment]
Fixed in revision 290. Now  %SEMESTERDATES% will expand according to the planningTerm. The email template text file not updated yet.
