### ISSUE TITLE
In eduoffice --> Faculty Cannot delete a faculty member

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#76]
Should be able to delete a faculty member (make sure that is is confirmed) Also, when deleting a faculty member all the relevant items in LectureTerm, TeachingPref, TARating need to be deleted

**Comment by pluskid** [comment]
Fixed in revision 321. Now we can delete a faculty in eduoffice with the red button right below his photo in the faculty tab.
