### ISSUE TITLE
More in courses 

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#77]
1) In each couse, make it possible to optionally identify a primary couse  (eg: 6.813/6.831)
If there is a primary, then don't don't make it appare in any TA functions. (in Staff, faculty and eduoffice)  
2) It would be nice to show all the secondary classes in the course name (i.e. instead of 6.813 show 6.813/6.831)

**Comment by pluskid** [comment]
Fixed in revision 323~325.
