### ISSUE TITLE
Additional TA type

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#88]
Can you make an additional TA type 1/2 time TA. 

1) add a corresponding letter for 1/2 time TA
2) Selecting a 1/2 TA should change the FTE to 1/2
3) Assigning a student to 1/2 TA slot should make his TA type 1/2 time TA

**Comment by samanamarasinghe** [comment]
1/2 TA for both grad and undergrad

**Comment by samanamarasinghe** [comment]
Undergrad 20 hrs max vs 10 hrs max

**Comment by samanamarasinghe** [comment]
Undergraduate TA (max 20 hours/week)
Undergraduate TA (max 10 hours/week)

**Comment by samanamarasinghe** [comment]
In setup also ask for the default FTE rate for each TA category. When you change from caregory A  to B. If the rate is of A, then change it to B. If the rate is something else, leave it alone.

**Comment by pluskid** [comment]
fixed in revision 355.
