### ISSUE TITLE
More Student TA status

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#89]
Can you add two more Student TA status that has to come after Accepted. They are
1) Appointment made
2) GO approve
3) GO hold

There is a state table that indicates which status are available as the next state from the current state

Offer Accepted --> Appointment Made --> Withdrawn, GO Approve, GO hold
Appointment Made, GO hold --> GO approve --> Withdrawn
Appointment Made -> GO hold --> GO approve, Appointment Made, Withdrawn

**Comment by samanamarasinghe** [comment]
Withdrawn misspelled in models.py

**Comment by pluskid** [comment]
done
