### ISSUE TITLE
Active and planning terms in DB

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#93]
Currently they are in the setup file. Thus, one need to modify the setup file by hand. It would be nice to be able to do that from the interface. (But with a lot of confirmation questions!) Perhaps from the Term Setup page or Setup Page.

**Comment by samanamarasinghe** [comment]
It is already in the database!! So now we need a way to advance that in Setup (with many times asking if you want to do it)

**Comment by samanamarasinghe** [comment]
When change terms, all the planning term courses become active term course. And active term courses become done courses.

**Comment by samanamarasinghe** [comment]
If the course is only proposed, delete it from courseterm

**Comment by samanamarasinghe** [comment]
In student. All curr_stta should become null

**Comment by pluskid** [comment]
fixed in revision 350.
