### ISSUE TITLE
Need the TA slots allocated for the new page

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#95]
I am creating a new page called staff_course_list for the students to see the classes, how many TA slots allocated and how many TA slots are still available. Need to calculate the # of TA slots still avaiable. (We do something similar in Summary by Class page in eduoffice, but that is dynamic since the slots can be changed from that page. We need more of a static calculation here.)

**Comment by pluskid** [comment]
done
