### ISSUE TITLE
1/2 TAs (both grad and undergrad) are counted as full

### ISSUE THREAD

**Issue by samanamarasinghe** [mit-eecs/issue-tracker#99]
In Summary by Class --> TAs assigned so far
TA Selection --> TAs assigned so far

**Comment by samanamarasinghe** [comment]
One way to do this might be to add another field to the FTE table. A boolean field say half_slot. And count it as half a slot if that flag is true. So there is a clear separation between FTE and slots and slots are done nicely than hard cording it.

**Comment by pluskid** [comment]
In revision 362: now both `summary by class` and `ta selection` will count half TA as only 0.5.
